### PR TITLE
Add thresholds for NextSeq 2000

### PR DESCRIPTION
**Pull request by chuan-wang**
There will be a big validation for NextSeq 2000.

### CODE REVIEW

**Comment by aanil** [comment]
Would the Q30 values change for the new NextSeq chemistries?

**Comment by chuan-wang** [comment]
> Would the Q30 values change for the new NextSeq chemistries?

No, according to Illumina's specifications the Q30 criteria are the same as NextSeq 500/550.

**Review by aanil — APPROVED** [review]
👍

**Comment by aanil** [comment]
Ok, great!

**Pull request merged**
