### PR TITLE
AVITI manifest improvements

### PR DESCRIPTION
**Pull request by kedhammar**
For AVITI manifest generation: make PhiX manifest variant, fix udf typo, remove unused func, clarify var names

### CODE REVIEW

**Comment by chuan-wang** [comment]
Hi @kedhammar, there one more thing for us to fix. For the following cases index 2 need to be converted to the reverse complementary form:

(1) All inhouse-prepared libraries
(2) User submitted libraries with special indexes that match with `TENX_DUAL_PAT` and `SMARTSEQ_PAT`.

Please refer to the [codes for MiSeq](https://github.com/SciLifeLab/scilifelab_epps/blob/21ce4aa079245fcab92483c21fb9c8761ec05654/scripts/samplesheet_generator.py#L378-L383) as example.

**Review by chuan-wang — CHANGES_REQUESTED** [review]
Changes required.

**Comment by kedhammar** [comment]
> Changes required.

How's this? Not tested. 

[2bc45ad](https://github.com/SciLifeLab/scilifelab_epps/pull/374/commits/2bc45adbd4f70eb8443ab651c7d6609ced74ad8a)

**Comment by chuan-wang** [comment]
``> > Changes required.
> 
> How's this @chuan-wang? Not tested.
> 
> [2bc45ad](https://github.com/SciLifeLab/scilifelab_epps/pull/374/commits/2bc45adbd4f70eb8443ab651c7d6609ced74ad8a)

Hi, the logic should be the opposite:

```
# Special cases to reverse-complement index2
if not user_library or (
    user_library
    and (
        TENX_DUAL_PAT.findall(lims_label)
        or SMARTSEQ_PAT.findall(lims_label)
    )
):
    logging.info(f"Reverse-complementing index2 of {sample.name}.")
    row["Index2"] = revcomp(row["Index2"])

```

**Comment by kedhammar** [comment]
> ``> > Changes required.
> 
> > How's this @chuan-wang? Not tested.
> > [2bc45ad](https://github.com/SciLifeLab/scilifelab_epps/pull/374/commits/2bc45adbd4f70eb8443ab651c7d6609ced74ad8a)
> 
> Hi, the logic should be the opposite:
> 
> ```
> # Special cases to reverse-complement index2
> if not user_library or (
>     user_library
>     and (
>         TENX_DUAL_PAT.findall(lims_label)
>         or SMARTSEQ_PAT.findall(lims_label)
>     )
> ):
>     logging.info(f"Reverse-complementing index2 of {sample.name}.")
>     row["Index2"] = revcomp(row["Index2"])
> ```

Oop, that's right 👀 

[ab77d5e](https://github.com/SciLifeLab/scilifelab_epps/pull/374/commits/ab77d5ee87a756e4a934b302c41d43ac2570139d)

**Review by chuan-wang — APPROVED** [review]

**Pull request merged**
