### PR TITLE
Update BioAnalyzer step

### PR DESCRIPTION
**Pull request by kedhammar**
Part of GA project GA_23_15 and validation 23_14.

### CODE REVIEW

**Comment by kedhammar** [comment]
> Hi @kedhammar, the changes look good! Just to double check: have you looked into the xml output files from BA DNA and RNA (nano, pico, smRNA) assays? I'm a little bit concerned that they may have different data structure (though I'm not sure whether it is true).

I will check this with Orlando

**Comment by alneberg** [comment]
Looks good to me as well! Have you looked into the question Chuan had?

**Comment by kedhammar** [comment]
@chuan-wang @alneberg 
I have not, however OC has mailed Agilent to ask.

Any idea where I could obtain the different .xml files to try it out?

**Comment by chuan-wang** [comment]
@kedhammar The only place I can think of is the Bioanalyzer PC in the clean room. If they haven't cleared the old data, there should be old runs with BioAnalyzer RNA Nano, Pico and Small RNA kits.

**Comment by chuan-wang** [comment]
Hi @kedhammar, is there more concern about the BioAnalyzer RNA Nano, Pico and Small RNA assay? If not we maybe we should merge this PR? The LIMS document has been published.

**Comment by kedhammar** [comment]
> Hi @kedhammar, is there more concern about the BioAnalyzer RNA Nano, Pico and Small RNA assay? If not we maybe we should merge this PR? The LIMS document has been published.

@chuan-wang Since the validation is approved I'm fine with merging. Let me just fix the merge conflicts.

We haven't looked extensively for any differences between the XML outputs of different methods, but worst case scenario is that the EPP doesn't work and I fix it as the need arises. I can see no way that it would pull "false" results and all information can be filled in manually by the operator with little effort as we have done previously.

**Comment by chuan-wang** [comment]
> > Hi @kedhammar, is there more concern about the BioAnalyzer RNA Nano, Pico and Small RNA assay? If not we maybe we should merge this PR? The LIMS document has been published.
> 
> @chuan-wang Since the validation is approved I'm fine with merging. Let me just fix the merge conflicts.
> 
> We haven't looked extensively for any differences between the XML outputs of different methods, but worst case scenario is that the EPP doesn't work and I fix it as the need arises. I can see no way that it would pull "false" results and all information can be filled in manually by the operator with little effort as we have done previously.

👍

**Pull request merged**
