### PR TITLE
Remove obsoleted EPP scripts; Refactor UDF names for library prep amount

### PR DESCRIPTION
**Pull request by chuan-wang**
Hi Alfred (@kedhammar), the lab wants to refactor the UDF for recording the input amount for library prep:

`Amount taken (ng) or Target amount (ng) -> Amount for prep (ng)`

Then a new UDF for recording the actual amount that is taken from user's plate:

`Amount taken from plate (ng)`

Would you mind looking into the Zika part since I'm not familiar with them? Thanks!

/Chuan

### CODE REVIEW

**Review by kedhammar — CHANGES_REQUESTED** [review]
- `fetch_output_udfs()` and `assert_udfs()` can be removed from `zika_utils.py`
- Is this being setup on stage prior to deployment? If so I could test the Zika scripts.

**Review by kedhammar — APPROVED** [review]

**Comment by chuan-wang** [comment]
> * `fetch_output_udfs()` and `assert_udfs()` can be removed from `zika_utils.py`
These have been removed.
> * Is this being setup on stage prior to deployment? If so I could test the Zika scripts.
I have implemented the changes on the "QIAseq miRNA Library Prep" and "TruSeq RNA Library Prep V2" protocols on LIMS-stage. Could you use the former one for testing Zika functions?

I will also start a verification for this.

**Comment by kedhammar** [comment]
> I have implemented the changes on the "QIAseq miRNA Library Prep" and "TruSeq RNA Library Prep V2" protocols on LIMS-stage. Could you use the former one for testing Zika functions?

As long as it's pushed through the pre-pooling step it should work :)

**Comment by chuan-wang** [comment]
> > I have implemented the changes on the "QIAseq miRNA Library Prep" and "TruSeq RNA Library Prep V2" protocols on LIMS-stage. Could you use the former one for testing Zika functions?
> 
> As long as it's pushed through the pre-pooling step it should work :)

I saw for the QIAseq, SMARTer and Amplicon protocols, the script is using the `norm` function for preparing workset. Or maybe I missunderstood? The pooling part was not touched.

**Comment by kedhammar** [comment]
> I saw for the QIAseq, SMARTer and Amplicon protocols, the script is using the `norm` function for preparing workset. Or maybe I missunderstood? The pooling part was not touched.

Oh no it's I who misunderstood. Zika should indeed be available to use for normalization in these steps.

**Pull request merged**
